# Generated by Django 3.2.12 on 2022-09-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cover_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='detail_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('outpatient', models.IntegerField(null=True)),
                ('hospitalization', models.IntegerField(null=True)),
                ('operation', models.IntegerField(null=True)),
                ('patella', models.IntegerField(null=True)),
                ('skin_disease', models.IntegerField(null=True)),
                ('dental', models.IntegerField(null=True)),
                ('urinary', models.IntegerField(null=True)),
                ('liability', models.IntegerField(null=True)),
                ('insurance_choice', models.IntegerField(null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_user', to='insurance.breed')),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('insurance_name', models.CharField(max_length=100)),
                ('company_url', models.CharField(max_length=100)),
                ('company_logo', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
                ('etc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='insurance_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('basic', models.JSONField(null=True)),
                ('special', models.JSONField(null=True)),
                ('all_cover', models.JSONField(null=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_detail', to='insurance.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300, null=True)),
                ('detail_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='insurance.detail_user')),
                ('insurance_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='insurance.insurance_detail')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_url', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('cover_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='insurance.cover_type')),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='insurance.cover_type')),
            ],
        ),
        migrations.CreateModel(
            name='cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wild', models.BooleanField(null=True)),
                ('cover_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='insurance.cover_type')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='insurance.insurance')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='disease',
            field=models.ManyToManyField(related_name='breed', to='insurance.disease'),
        ),
    ]
