# Generated by Django 3.2.12 on 2022-09-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='company_url',
            field=models.CharField(max_length=300),
        ),
    ]
